// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("h3", {
              children: "Hi, Athma!!"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
